POST http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
    "username": "ttiusanen",
    "password": "",
    "email": ""
}

###


POST http://localhost:8080/api/register HTTP/1.1
content-type: application/json

{
    "username": "testuser",
    "password": "testpw",
    "email": "testuser@domain.com"
}

###

POST http://localhost:8080/api/login HTTP/1.1
content-type: application/json

{
    "username": "ttiusanen",
    "password": "passu01"
}

###

GET http://localhost:8080/api/users HTTP/1.1
content-type: application/json


###
# Test with container IP
# 172.17.0.2 is the Docker container ip 
# 8080 is the exposed port from the container
POST http://172.17.0.2:8080/api/register HTTP/1.1
content-type: application/json

{
    "username": "test",
    "password": "testpw",
    "email": "testuser@domain.com"
}